language: node_js
node_js:
 - "node"
 - "6"
services:
 - postgresql
before_script:
 - psql -c "CREATE DATABASE recipesdb;" -U postgres
 - psql -c "CREATE PASSWORD 'dehydrogenase';" -U postgres
cache:
  directories:
   - node_modules