language: node_js
node_js:
 - "node"
 - "6"
services:
 - postgresql
before_script:
 - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
 - sequelize db:migrate
cache:
  directories:
   - node_modules