
export const LOAD_RECIPE_SUCCESS = 'LOAD_RECIPE_SUCCESS';
export const LOAD_ONE_RECIPE = 'LOAD_ONE_RECIPE';
export const GET_VOTE = 'GET_VOTE';
export const GET_REVIEW = 'GET_REVIEW';
export const GET_MESSAGE = "GET_MESSAGE";
export const LOAD_ALL_REVIEWS = "LOAD_ALL_REVIEWS";
export const LOAD_PAGINATE = "LOAD_PAGINATE";
export const APP_MESSAGE = "APP_MESSAGE";
export const LOAD_FAVORITE_RECIPE = "LOAD_FAVORITE_RECIPE";
export const LOAD_ALL_USERS = "LOAD_ALL_USERS";
export const LOAD_ONE_USER = "LOAD_ONE_USER";
